In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [6]:
a.ndim

1

In [7]:
len(a.shape)

1

In [9]:
b = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]
    ])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [16]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [21]:
s = np.random.random((4,5))

In [26]:
s

array([[0.84507836, 0.48965149, 0.02316377, 0.92347815, 0.16411937],
       [0.50758268, 0.45391039, 0.84250686, 0.58978185, 0.36717113],
       [0.03735754, 0.04483469, 0.17671886, 0.42138368, 0.5063651 ],
       [0.43906344, 0.81584581, 0.62728159, 0.44464453, 0.19051732]])

In [22]:
np.arange(3,10,1)

array([3, 4, 5, 6, 7, 8, 9])

In [27]:
center = s[1:3, 1:4]
center = 0

In [30]:
s[1:3, 1:4] = 0

In [31]:
s

array([[0.84507836, 0.48965149, 0.02316377, 0.92347815, 0.16411937],
       [0.50758268, 0.        , 0.        , 0.        , 0.36717113],
       [0.03735754, 0.        , 0.        , 0.        , 0.5063651 ],
       [0.43906344, 0.81584581, 0.62728159, 0.44464453, 0.19051732]])

In [33]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.array([a[0,1], a[1,1], a[2,1]])

array([2, 5, 8])

In [37]:
a[[0,1,2],[1,1,1]]

array([2, 5, 8])

In [38]:
x = np.array([1,2,3], dtype="f")

In [39]:
x

array([1., 2., 3.], dtype=float32)

In [40]:
x.dtype

dtype('float32')

In [44]:
x = x.astype(np.float64)

In [45]:
x.dtype

dtype('float64')

In [46]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [47]:
c = a + b

In [55]:
d = a**4

In [56]:
d

array([[   0,    1,   16],
       [  81,  256,  625],
       [1296, 2401, 4096]])

In [59]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

b = np.array([1, 2, 3])

c = np.dot(a,b)

c

array([ 8, 26, 44])

In [61]:
x = np.random.randint(0, 10, (8,10))

In [62]:
x

array([[1, 1, 6, 4, 5, 6, 9, 0, 9, 1],
       [4, 1, 7, 8, 6, 6, 5, 9, 4, 2],
       [8, 7, 2, 9, 2, 9, 8, 3, 8, 4],
       [2, 0, 0, 2, 8, 2, 2, 1, 6, 9],
       [4, 2, 1, 0, 8, 6, 6, 1, 8, 4],
       [3, 0, 5, 3, 2, 9, 9, 0, 0, 0],
       [1, 4, 7, 7, 1, 2, 2, 4, 7, 7],
       [8, 7, 6, 0, 4, 9, 2, 5, 7, 9]])

In [63]:
x.mean()

4.45

In [64]:
x.var()

9.3225

In [65]:
x.std()

3.053276928154405

In [66]:
x.max()

9

In [67]:
x.mean(axis=1)

array([4.2, 5.2, 6. , 3.2, 4. , 3.1, 4.2, 5.7])

In [68]:
X = np.array([
    [2, 3],
    [2, 5],
    [3, 4],
    [5, 9],
])

X

array([[2, 3],
       [2, 5],
       [3, 4],
       [5, 9]])

In [69]:
ones = np.ones((X.shape[0], 1))

In [71]:
X = np.concatenate((ones, X), axis=1)
X

array([[1., 2., 3.],
       [1., 2., 5.],
       [1., 3., 4.],
       [1., 5., 9.]])

In [72]:
t = np.array([1,5,6,8])

In [73]:
xx = np.dot(X.T,X)
xx

array([[  4.,  12.,  21.],
       [ 12.,  42.,  73.],
       [ 21.,  73., 131.]])

In [75]:
xx_inv = np.linalg.inv(xx)
xx_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [76]:
xt = np.dot(X.T,t)
xt

array([ 20.,  70., 124.])

In [77]:
w = np.dot(xx_inv, xt)
w

array([-0.14285714,  0.71428571,  0.57142857])