In [1]:
import numpy as np
import theano
import theano.tensor as tensor

In [2]:
def main():
    a=tensor.fscalar(name="a")
    b=tensor.fvector(name="b")
    c=tensor.fmatrix(name="c")
    d=tensor.iscalar(name="d")
    e=tensor.ivector(name="e")
    f=tensor.imatrix(name="f")

In [3]:
main()

In [8]:
def main():
    x=tensor.dscalar(name="x")
    y=tensor.dscalar(name="y")
    f=theano.function(inputs=[x,y],outputs=[x+y])
    return f(1,2)[0]

In [9]:
print(main())

3.0


In [10]:
def main():
    c=tensor.dscalar(name="c")
    x=c+2
    y=c*c
    f=theano.function(inputs=[c],outputs=[x**2+y])
    return f(2)

In [11]:
print(main())

[array(20.)]


In [18]:
def main():
    x=tensor.dscalar(name="x")
    y=tensor.dscalar(name="y")
    z=(x+4*y)**3
    gzx=tensor.grad(cost=z,wrt=x)
    gzy=tensor.grad(cost=z,wrt=y)
    fgzx=theano.function(inputs=[x,y],outputs=[gzx])
    fgzy=theano.function(inputs=[x,y],outputs=[gzy])
    return fgzx(8,3)[0],fgzy(4,2)[0]

In [19]:
print(main())

(array(1200.), array(1728.))


In [37]:
def main():
    x=tensor.dscalar()
    c=theano.shared(value=3)
    f=theano.function(inputs=[x],outputs=[c*x])
    print(f(2)[0])
    c.set_value(4)
    print(f(2)[0])

In [38]:
main()

6.0
8.0


In [27]:
def main():
    c=theano.shared(value=np.array([0]),name="c")
    f=theano.function(inputs=[],outputs=[c*c],updates=[(c,c+1)])
    for i in range(4):
        print(c.get_value(), f()[0])

In [28]:
main()

[0] [0]
[1] [1]
[2] [4]
[3] [9]


In [39]:
def main():
    tsa=tensor.lscalar("tsa")
    tsn=tensor.iscalar("tsn")
    lioutput,liupdate=theano.scan(fn=fna,
                                  sequences=None,
                                 outputs_info=tsa,
                                 non_sequences=None,
                                 n_steps=tsn)
    fnb=theano.function(inputs=[tsa,tsn],outputs=lioutput,updates=liupdate)
    print(fnb(9,10))
def fna(tsa):
    return 2+tsa

In [40]:
main()

[11 13 15 17 19 21 23 25 27 29]


In [41]:
lr=theano.shared(value=np.float32(0.4),name="lr")
print(lr.eval())

0.4


In [46]:
def main():
    x=tensor.dvector(name="x")
    w=theano.shared(value=np.random.rand(4),name="w")
    y=tensor.sum((x-w)**2)+1
    gyw=tensor.grad(cost=y,wrt=w)
    lr=theano.shared(value=np.float32(0.4),name="lr")
    f=theano.function(inputs=[x],outputs=[y],updates=[(w,w-lr*gyw)])
    for i in range(30):
        print("Epoch: ",i+1," y=",f([1,2,3,4])[0],"\tw=",w.get_value(),sep="")
        if (i+1)%5==0: 
            lr.set_value(lr.get_value()*np.float32(0.9))

In [44]:
t=np.random.rand(4)

In [45]:
print(t)

[0.71961274 0.55091478 0.91859857 0.47790642]


In [47]:
main()

Epoch: 1 y=17.97301997848473	w=[0.91462803 1.79494477 2.56486055 3.3364954 ]
Epoch: 2 y=1.6789207182057249	w=[0.98292561 1.95898896 2.91297212 3.86729909]
Epoch: 3 y=1.0271568254908827	w=[0.99658512 1.99179779 2.98259442 3.97345982]
Epoch: 4 y=1.0010862728901415	w=[0.99931702 1.99835956 2.99651889 3.99469196]
Epoch: 5 y=1.000043450910426	w=[0.9998634  1.99967191 2.99930378 3.99893839]
Epoch: 6 y=1.0000017380362098	w=[0.99996175 1.99990814 2.99980506 3.99970275]
Epoch: 7 y=1.000000136262069	w=[0.99998929 1.99997428 2.99994542 3.99991677]
Epoch: 8 y=1.0000000106829485	w=[0.999997   1.9999928  2.99998472 3.9999767 ]
Epoch: 9 y=1.0000000008375434	w=[0.99999916 1.99999798 2.99999572 3.99999347]
Epoch: 10 y=1.0000000000656635	w=[0.99999976 1.99999944 2.9999988  3.99999817]
Epoch: 11 y=1.000000000005148	w=[0.99999992 1.9999998  2.99999958 3.99999936]
Epoch: 12 y=1.000000000000638	w=[0.99999997 1.99999993 2.99999985 3.99999977]
Epoch: 13 y=1.000000000000079	w=[0.99999999 1.99999998 2.99999995 

In [69]:
def main():
    #x=theano.shared(value=np.random.rand(),name="x")
    x=theano.shared(value=3.0,name="x")
    y=(x-1)**2
    gyx=tensor.grad(cost=y,wrt=x)
    lr=theano.shared(value=np.float32(0.4),name="lr")
    f=theano.function(inputs=[],outputs=[y],updates=[(x,x-lr*gyx)])
    for i in range(30):
        print(f()[0], x.eval())
        if (i+1)%5==0:
            lr.set_value(lr.get_value()*np.float32(0.9))
            

In [70]:
main()

4.0 1.399999976158142
0.15999998092651424 1.0799999904632571
0.00639999847412123 1.0159999971389773
0.0002559999084472806 1.0031999992370606
1.0239995117188436e-05 1.0006399998092652
4.095997558595085e-07 1.0001791999664307
3.211262796875558e-08 1.0000501759961549
2.5176305901331732e-09 1.0000140492804785
1.9738228196483284e-10 1.0000039337989695
1.547477433210622e-11 1.0000011014638335
1.2132225764533994e-12 1.000000387715333
1.5032317940462443e-13 1.0000001364758195
1.8625649317573577e-14 1.0000000480394964
2.3077932125286366e-15 1.0000000169099055
2.859449032028699e-16 1.0000000059522878
3.54297297418973e-17 1.0000000024809141
6.154934973971742e-18 1.0000000010340453
1.0692496697025314e-18 1.0000000004309901
1.8575249428799096e-19 1.0000000001796367
3.22693619216803e-20 1.0000000000748726
5.605899133184309e-21 1.0000000000355735
1.2654770405770178e-21 1.0000000000169018
2.8567129222934254e-22 1.0000000000080305
6.448837103479607e-23 1.0000000000038154
1.455721952025078e-23 1.0000000

In [58]:
print(type(np.random.rand()))

<class 'float'>


In [101]:
x=theano.shared(value=False)
y=theano.shared(value=np.array([1.0,2.0]))
z=theano.shared(value=np.array([1.0,3.0]))

In [102]:
x_switch = tensor.switch(x,y,z)

In [103]:
print(x_switch.eval())

[1. 3.]


In [81]:
x_switch

Elemwise{switch,no_inplace}.0

In [104]:
print(np.random.rand(4,5))

[[0.93519732 0.93179939 0.36104762 0.09885824 0.93029486]
 [0.71422282 0.08937631 0.74645971 0.02972561 0.34077722]
 [0.20062984 0.77680836 0.30697642 0.46883034 0.92582715]
 [0.43660326 0.18707398 0.92482252 0.16411677 0.29437018]]
